# Optional variables:
# USER_DOX_CREATE_SUBDIRS
# USER_DOX_EXCLUDE_PATTERN
# USER_DOX_FILE_PATTERNS
# USER_DOX_PREDEFINED

SET (BUILD_DOCUMENTATION ON)
INCLUDE(${CMAKE_ROOT}/Modules/Documentation.cmake OPTIONAL)
IF (DOXYGEN)
# Checking DOT
	IF(DOT)
		SET(HAVE_DOT YES)
	ELSE(DOT)
		SET(HAVE_DOT NO)
	ENDIF(DOT)

# Checking language
	SET (LANG_IS_RU NO)
	IF (UNIX)
		STRING (REGEX MATCH "ru|RU" LANG $ENV{LANG})
		IF (DEFINED LANG)
			IF (LANG STREQUAL "ru" OR LANG STREQUAL "RU")
				SET (LANG_IS_RU YES)
			ENDIF (LANG STREQUAL "ru" OR LANG STREQUAL "RU")
		ENDIF (DEFINED LANG)
	ENDIF (UNIX)
	IF (LANG_IS_RU)
		SET (DOX_LANGUAGE Russian)
		SET (DOX_DOCS_INPUT rus)
	ELSE (LANG_IS_RU)
		SET (DOX_LANGUAGE English)
		SET (DOX_DOCS_INPUT eng)
	ENDIF (LANG_IS_RU)
	MESSAGE ("Documentation output language is ${DOX_LANGUAGE}")
# Checking OS
	IF (UNIX)
		SET (DOX_EXCLUDE_PATTERN Win.)
		SET (DOX_PREDEFINED linux)
	ELSE (UNIX)
		SET (DOX_EXCLUDE_PATTERN Lin.)
		SET (DOX_PREDEFINED WIN32)
	ENDIF (UNIX)
	SET (DOX_EXCLUDE_PATTERN ${DOX_EXCLUDE_PATTERN}*)
# Checking revision
	EXECUTE_PROCESS (COMMAND svn info ${PROJECT_SOURCE_DIR} OUTPUT_VARIABLE SVN_INFO)
	IF (SVN_INFO)
		STRING (REGEX MATCH "Revision: [0-9]+" SVN_REVISION ${SVN_INFO})
		STRING (REGEX MATCH "[0-9]+" SVN_REVISION ${SVN_REVISION})
	ENDIF (SVN_INFO)
# Setting some other variables, which user can change
	SET (DOX_FILE_PATTERNS "*.h *.cpp *.dox ${USER_DOX_FILE_PATTERNS}")
	SET (DOX_EXCLUDE_PATTERN "${DOX_EXCLUDE_PATTERN} */.svn*/ ${USER_DOX_EXCLUDE_PATTERN}")
	SET (DOX_PREDEFINED "${DOX_PREDEFINED} ${USER_DOX_PREDEFINED}")
	IF (DEFINED USER_DOX_CREATE_SUBDIRS)
		SET (DOX_CREATE_SUBDIRS ${USER_DOX_CREATE_SUBDIRS})
	ELSE (DEFINED USER_DOX_CREATE_SUBDIRS)
		SET (DOX_CREATE_SUBDIRS YES)
	ENDIF (DEFINED USER_DOX_CREATE_SUBDIRS)
# Configuring Doxyfile
	CONFIGURE_FILE(${PROJECT_SOURCE_DIR}/CMakeModules/Doxyfile.cmake
		${PROJECT_BINARY_DIR}/Doxyfile
	)
	ADD_CUSTOM_TARGET(DoxygenDoc ${DOXYGEN_EXECUTABLE}
		${PROJECT_BINARY_DIR}/Doxyfile
	)
	
	IF (WIN32)
		INSTALL (DIRECTORY ${PROJECT_BINARY_DIR}/docs/html DESTINATION doc)
	ELSE (WIN32)
		INSTALL (DIRECTORY ${PROJECT_BINARY_DIR}/docs/html DESTINATION share/doc/${PROJECT_NAME})
	ENDIF (WIN32)
	
ELSE (DOXYGEN)
	MESSAGE ("Doxygen is not found, documentation will NOT be built")
ENDIF (DOXYGEN)
