SET (LAPACK_PATHS    
   $ENV{PROGRAMFILES}/lapack
   $ENV{PROGRAMFILES}/Lapack
   $ENV{PROGRAMFILES}/LAPACK
   $ENV{LAPACKDIR}
   $ENV{LAPACK_DIR}   
   )
   
SET (WANTED_MODULE_NAME     Lapack)
SET (WANTED_INCLUDES		lapack.h)
SET (WANTED_INCLUDES_PATH   ${LAPACK_PATHS}/include) 
SET (WANTED_LIBRARIES       clapack_nowrap clapack)
SET (WANTED_LIBRARIES_PATH  ${LAPACK_PATHS}) 
INCLUDE (FindCommonModule)

SET (WANTED_MODULE_NAME     Blas)
SET (WANTED_INCLUDES		blas.h)
SET (WANTED_INCLUDES_PATH   ${LAPACK_PATHS}/include) 
SET (WANTED_LIBRARIES       BLAS_nowrap BLAS blas Blas)
SET (WANTED_LIBRARIES_PATH  ${LAPACK_PATHS}) 
INCLUDE (FindCommonModule)

SET (WANTED_MODULE_NAME     libf2c)
SET (WANTED_INCLUDES		libf2c.h)
SET (WANTED_INCLUDES_PATH   ${LAPACK_PATHS}/include) 
SET (WANTED_LIBRARIES       libf2c)
SET (WANTED_LIBRARIES_PATH  ${LAPACK_PATHS}) 
INCLUDE (FindCommonModule)

IF (LAPACK_FOUND AND BLAS_FOUND AND LIBF2C_FOUND)
	LIST (APPEND Lapack_LIBRARIES 
		${Blas_LIBRARIES}
		${libf2c_LIBRARIES}
	)
	LIST (APPEND Lapack_LIBRARY 
		${Blas_LIBRARY}
		${libf2c_LIBRARY}
	)
	SET (LAPACK_FOUND TRUE)
ELSE (LAPACK_FOUND AND BLAS_FOUND AND LIBF2C_FOUND)
	SET (LAPACK_FOUND FALSE)
ENDIF ()