SET (WANTED_MODULE_NAME     GLEW)
SET (WANTED_INCLUDES        GL/glew.h)

IF (GLEW_USE_STATIC_LIB)
	SET (WANTED_LIBRARIES "GLEWs" "glew32s")
ELSE (GLEW_USE_STATIC_LIB)
	SET (WANTED_LIBRARIES "GLEW" "glew32")
ENDIF (GLEW_USE_STATIC_LIB)

INCLUDE (FindCommonModule)