SET (DEVIL_PATHS    
    $ENV{PROGRAMFILES}/DevIL
    $ENV{DEVILDIR}
    $ENV{DEVIL_DIR}
)

SET (WANTED_MODULE_NAME     DevIL)
SET (WANTED_INCLUDES        IL/il.h)
SET (WANTED_LIBRARIES       IL DevIL)
SET (WANTED_INCLUDES_PATH	${DEVIL_PATHS})
SET (WANTED_LIBRARIES_PATH	${DEVIL_PATHS})
INCLUDE (FindCommonModule)

SET (WANTED_MODULE_NAME     ILU)
SET (WANTED_INCLUDES        IL/ilu.h)
SET (WANTED_LIBRARIES       ILU)
SET (WANTED_INCLUDES_PATH	${DEVIL_PATHS})
SET (WANTED_LIBRARIES_PATH	${DEVIL_PATHS})
INCLUDE (FindCommonModule)

SET (WANTED_MODULE_NAME     ILUT)
SET (WANTED_INCLUDES        IL/ilut.h)
SET (WANTED_LIBRARIES       ILUT)
SET (WANTED_INCLUDES_PATH	${DEVIL_PATHS})
SET (WANTED_LIBRARIES_PATH	${DEVIL_PATHS})
INCLUDE (FindCommonModule)

# setup variables
IF (ILU_FOUND)
	LIST (APPEND DevIL_LIBRARIES ${ILU_LIBRARY})
ENDIF (ILU_FOUND)

IF (ILUT_FOUND)
	LIST (APPEND DevIL_LIBRARIES ${ILUT_LIBRARY})
ENDIF (ILUT_FOUND)