SET (ACML_PATHS    
    $ENV{PROGRAMFILES}/acml
    $ENV{ACMLDIR}
    $ENV{ACML_DIR}
)

SET (WANTED_MODULE_NAME     ACML)
SET (WANTED_INCLUDES        acml.h)
IF (ACML_USE_STATIC_LIB)
	SET (WANTED_LIBRARIES libacml)
ELSE (ACML_USE_STATIC_LIB)
	SET (WANTED_LIBRARIES libacml_dll)
ENDIF (ACML_USE_STATIC_LIB)
SET (WANTED_INCLUDES_PATH	${ACML_PATHS})
SET (WANTED_LIBRARIES_PATH	${ACML_PATHS})
INCLUDE (FindCommonModule)